import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

async function loadDir(dir) {
  const full = path.join(root, dir);
  const files = (await readdir(full)).filter((f) => f.endsWith(".json")).sort();
  const out = [];
  for (const f of files) {
    out.push({ file: `${dir}/${f}`, data: JSON.parse(await readFile(path.join(full, f), "utf8")) });
  }
  return out;
}

const recipes = await loadDir("examples");
const models = await loadDir("models");
const failures = await loadDir("failures");

const recipeById = new Map(recipes.map((r) => [r.data.id, r.data]));
const modelById = new Map(models.map((m) => [m.data.id, m.data]));

const problems = [];

// Referential integrity: every cross-reference must resolve.
for (const { file, data } of models) {
  for (const run of data.evidence?.localRuns || []) {
    if (!recipeById.has(run.recipeId)) {
      problems.push(`${file}: localRuns references unknown recipeId "${run.recipeId}"`);
    }
  }
}
for (const { file, data } of failures) {
  for (const id of data.relatedModelIds || []) {
    if (!modelById.has(id)) problems.push(`${file}: relatedModelIds references unknown model "${id}"`);
  }
  for (const id of data.relatedRecipeIds || []) {
    if (!recipeById.has(id)) problems.push(`${file}: relatedRecipeIds references unknown recipe "${id}"`);
  }
  if (!data.measuredDifference?.requested || !data.measuredDifference?.measured) {
    problems.push(`${file}: measuredDifference must state both requested and measured`);
  }
}

// Honesty guard: a not-run model must never carry a score.
const SCORE_KEYS = ["qualityScore", "score", "rank", "winRate", "successRate", "preference", "elo"];
for (const { file, data } of models) {
  if (data.status !== "verified") {
    const found = SCORE_KEYS.filter((k) => k in (data.publishedSpec || {}));
    if (found.length) problems.push(`${file}: status "${data.status}" must not carry scores: ${found.join(", ")}`);
  }
}

// Measured values may only come from a verified recipe.
const verifiedRecipeIds = new Set(
  recipes.filter(({ data }) => data.output?.sha256).map(({ data }) => data.id),
);

function fmtDuration(s) {
  if (s == null) return "—";
  return `${Number(s).toFixed(2)} s`;
}

function yesNo(v) {
  if (v === true) return "yes";
  if (v === false) return "no";
  return "unknown";
}

function specCell(v, fallback = "not published") {
  if (v === null || v === undefined || (Array.isArray(v) && v.length === 0)) return fallback;
  return Array.isArray(v) ? v.join(", ") : String(v);
}

// ---------- model matrix ----------
const modelRows = models
  .map(({ data: m }) => {
    const verifiedRecipes = (m.evidence?.localRuns || [])
      .map((r) => recipeById.get(r.recipeId))
      .filter(Boolean);
    const measured = verifiedRecipes.map((r) => r.output?.measured).filter(Boolean);
    const durations = measured.map((x) => x.durationSeconds).filter((x) => x != null);
    const sizes = [...new Set(measured.map((x) => `${x.width}x${x.height}`))];
    return {
      name: m.name,
      provider: m.provider,
      status: m.status,
      modality: m.modality.join(", "),
      access: m.access.type,
      specResolutions: specCell(m.publishedSpec?.resolutions),
      specRatios: specCell(m.publishedSpec?.aspectRatios),
      specMaxDuration: m.publishedSpec?.maxDurationSeconds ?? "not published",
      specAudio: yesNo(m.publishedSpec?.nativeAudio),
      price: m.pricing?.publicRate || "not published",
      measuredSizes: sizes.length ? sizes.join(", ") : "no local run",
      measuredDurations: durations.length ? durations.map(fmtDuration).join(", ") : "no local run",
      runs: verifiedRecipes.length,
    };
  })
  .sort((a, b) => {
    if (a.status === "verified" && b.status !== "verified") return -1;
    if (b.status === "verified" && a.status !== "verified") return 1;
    return a.provider.localeCompare(b.provider);
  });

const statusLabel = { verified: "Verified local run", "not-run": "No local run", deprecated: "Deprecated" };

const matrixMd = [
  "# AI video model matrix",
  "",
  `Generated by \`npm run build\`. Do not edit by hand. Source records: \`models/*.json\`.`,
  "",
  `Last regenerated: ${new Date().toISOString().slice(0, 10)}`,
  "",
  "## How to read this table",
  "",
  "- **Verified local run** means this repository holds at least one recipe whose public input and output were re-downloaded and matched by SHA-256. Columns prefixed **Measured** come from those files.",
  "- **No local run** means the repository has not run this model. Spec and price columns are **vendor-published figures copied from public documentation**, not measurements, and carry no quality or speed score of any kind.",
  "- Published spec and measured values are deliberately separate columns. A request value is a target; the measured value is what came back.",
  "",
  "| Model | Provider | Evidence | Mode | Access | Spec: resolutions | Spec: ratios | Spec: max duration | Spec: audio | Published price | Measured size | Measured duration | Verified runs |",
  "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
  ...modelRows.map((r) =>
    [
      "",
      r.name,
      r.provider,
      statusLabel[r.status] || r.status,
      r.modality,
      r.access,
      r.specResolutions,
      r.specRatios,
      r.specMaxDuration,
      r.specAudio,
      r.price.replace(/\|/g, "\\|"),
      r.measuredSizes,
      r.measuredDurations,
      String(r.runs),
    ]
      .map((c) => String(c).replace(/\|/g, "\\|"))
      .join(" | ")
      .concat(" |"),
  ),
  "",
  "## Access constraints",
  "",
  ...models.map(({ data: m }) => {
    const docs = m.access.documentationUrl ? ` Docs: ${m.access.documentationUrl}` : "";
    return `- **${m.name}** (${m.provider}, ${statusLabel[m.status] || m.status}): ${m.access.regionNotes}${docs}`;
  }),
  "",
].join("\n");

// ---------- failure catalogue ----------
const sevOrder = { high: 0, medium: 1, low: 2 };
const failureRows = [...failures]
  .map(({ data: f }) => f)
  .sort((a, b) => (sevOrder[a.severity] ?? 9) - (sevOrder[b.severity] ?? 9));

const failuresMd = [
  "# AI video failure catalogue",
  "",
  "Failure modes observed in this project's own runs. Every entry states what was requested, what was measured, how to detect it, and what to do instead.",
  "",
  `Generated by \`npm run build\`. Do not edit by hand. Source records: \`failures/*.json\`.`,
  "",
  `${failureRows.length} records. Severity counts: ${["high", "medium", "low"]
    .map((s) => `${s} ${failureRows.filter((f) => f.severity === s).length}`)
    .join(", ")}.`,
  "",
  "| Failure | Mode | Severity | Status | Requested | Measured |",
  "|---|---|---|---|---|---|",
  ...failureRows.map((f) =>
    [
      "",
      f.title,
      f.mode,
      f.severity,
      f.status,
      f.measuredDifference.requested,
      f.measuredDifference.measured,
    ]
      .map((c) => String(c).replace(/\|/g, "\\|"))
      .join(" | "),
  ),
  "",
  ...failureRows.flatMap((f) => {
    const modelsNamed = (f.relatedModelIds || []).map((id) => modelById.get(id)?.name || id);
    const recipesNamed = (f.relatedRecipeIds || []).map((id) => {
      const r = recipeById.get(id);
      return r ? `[${r.title}](../examples/${id.replace(/-[a-z0-9.]+$/, "")}.json)` : id;
    });
    return [
      `## ${f.title}`,
      "",
      `- **Mode:** ${f.mode}`,
      `- **Severity:** ${f.severity}`,
      `- **Status:** ${f.status}`,
      `- **First observed:** ${f.firstObservedAt}`,
      modelsNamed.length ? `- **Models:** ${modelsNamed.join(", ")}` : null,
      recipesNamed.length ? `- **Evidence recipes:** ${recipesNamed.join(", ")}` : null,
      "",
      `**Symptom.** ${f.symptom}`,
      "",
      `**Reproduction.** ${f.reproduction}`,
      "",
      `**Detection.** ${f.detection}`,
      "",
      `**Mitigation.** ${f.mitigation}`,
      "",
      `**Why it matters.** ${f.whyItMatters}`,
      "",
      ...(f.notes?.length ? ["**Notes.**", ...f.notes.map((n) => `- ${n}`), ""] : []),
    ].filter((x) => x !== null);
  }),
].join("\n");

// ---------- parameter matrix from real recipes ----------
const paramMd = [
  "# Request parameter vs measured output",
  "",
  "Every row is a real request this project submitted. The point of this table is the mismatch column: a request parameter is a target, not a promise.",
  "",
  `Generated by \`npm run build\`. Do not edit by hand. Source records: \`examples/*.json\`.`,
  "",
  "| Recipe | Model | Requested | Measured | Mismatch |",
  "|---|---|---|---|---|",
  ...recipes.map(({ data: r }) => {
    const req = r.request.parameters || {};
    const m = r.output.measured;
    const requestedBits = [
      req.ratio || req.aspectRatio ? `ratio ${req.ratio || req.aspectRatio}` : null,
      req.resolution ? `resolution ${req.resolution}` : null,
      req.durationSeconds ? `duration ${req.durationSeconds}s` : null,
    ].filter(Boolean);
    const measuredBits = [
      m.width && m.height ? `${m.width}x${m.height}` : null,
      m.durationSeconds ? `${m.durationSeconds.toFixed(2)}s` : null,
      m.framesPerSecond ? `${m.framesPerSecond} fps` : null,
    ].filter(Boolean);
    const mismatches = [];
    if (req.ratio === "9:16" && m.width && m.height && m.width / m.height !== 9 / 16) {
      mismatches.push(`requested 9:16, measured ${m.width}x${m.height}`);
    }
    if (req.resolution && m.height) {
      const want = Number(String(req.resolution).toLowerCase().replace("p", ""));
      const longEdge = Math.max(m.width || 0, m.height);
      if (!Number.isNaN(want) && Math.abs(want - longEdge) > 2) {
        mismatches.push(`requested ${req.resolution}, measured long edge ${longEdge}`);
      }
    }
    if (req.durationSeconds && m.durationSeconds && Math.abs(Number(req.durationSeconds) - m.durationSeconds) > 0.2) {
      mismatches.push(`requested ${req.durationSeconds}s, measured ${m.durationSeconds.toFixed(2)}s`);
    }
    return [
      "",
      r.title,
      `\`${r.request.model}\``,
      requestedBits.join(", ") || "not recorded",
      measuredBits.join(", "),
      mismatches.length ? mismatches.join("; ") : "none observed",
    ]
      .map((c) => String(c).replace(/\|/g, "\\|"))
      .join(" | ");
  }),
  "",
  "Note: the H3 rows show a genuine ratio mismatch. The Wan 3.0 row honors its requested duration and resolution but its public artifact is a lossy derivative, which is recorded separately in the failure catalogue.",
  "",
].join("\n");

const docsDir = path.join(root, "docs");
await mkdir(docsDir, { recursive: true });
await writeFile(path.join(docsDir, "MODEL_MATRIX.md"), matrixMd);
await writeFile(path.join(docsDir, "FAILURES.md"), failuresMd);
await writeFile(path.join(docsDir, "PARAMETER_MATRIX.md"), paramMd);

const verifiedModels = models.filter(({ data }) => data.status === "verified").length;

if (problems.length) {
  console.error(`\nIntegrity problems (${problems.length}):`);
  for (const p of problems) console.error(`  - ${p}`);
  process.exitCode = 1;
} else {
  console.log(`Integrity OK: ${recipes.length} recipes, ${models.length} models (${verifiedModels} verified), ${failures.length} failure records.`);
}
console.log("Wrote docs/MODEL_MATRIX.md, docs/FAILURES.md, docs/PARAMETER_MATRIX.md");
